default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app
  username: postgres
  password: sssss

test:
  <<: *default
  database: recipe_app
  username: postgres
  password: sssss


production:
  <<: *default
  database: recipe_app
  username: postgres
  password: sssss

